# Generated by Django 5.2.7 on 2025-11-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_more_info', 'Needs More Information')], default='submitted', max_length=20)),
                ('document_type', models.CharField(choices=[('identity', 'Identity Document'), ('business_license', 'Business License'), ('tax_document', 'Tax Document'), ('address_proof', 'Address Proof'), ('bank_statement', 'Bank Statement')], max_length=50)),
                ('document_file', models.FileField(upload_to='kyc_documents/')),
                ('document_metadata', models.JSONField(blank=True, default=dict)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('activity_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KYC Request',
                'verbose_name_plural': 'KYC Requests',
                'db_table': 'kyc_requests',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('kyc_data', models.JSONField(blank=True, default=dict)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('payout_info', models.JSONField(blank=True, default=dict)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('tier_updated_at', models.DateTimeField(auto_now_add=True)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('account_health_score', models.PositiveIntegerField(default=100)),
                ('health_last_evaluated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('supports_international_shipping', models.BooleanField(default=False)),
                ('return_policy', models.TextField(blank=True)),
                ('shipping_policy', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
                'db_table': 'seller_profiles',
            },
        ),
        migrations.CreateModel(
            name='StoreFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_products', models.BooleanField(default=True)),
                ('notify_price_drops', models.BooleanField(default=True)),
                ('notify_restock', models.BooleanField(default=True)),
                ('notify_campaigns', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Store Follow',
                'verbose_name_plural': 'Store Follows',
                'db_table': 'store_follows',
            },
        ),
    ]
