# Generated by Django 5.2.7 on 2025-11-02 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sellers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycrequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='storefollow',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='storefollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['verification_status'], name='seller_prof_verific_b44370_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['tier'], name='seller_prof_tier_3392b6_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['is_active', 'featured'], name='seller_prof_is_acti_41223b_idx'),
        ),
        migrations.AddIndex(
            model_name='kycrequest',
            index=models.Index(fields=['status'], name='kyc_request_status_5b6087_idx'),
        ),
        migrations.AddIndex(
            model_name='kycrequest',
            index=models.Index(fields=['seller', 'status'], name='kyc_request_seller__43d856_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storefollow',
            unique_together={('user', 'seller')},
        ),
    ]
