# Generated by Django 5.2.7 on 2025-11-02 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('overall', 'Overall Health'), ('performance', 'Performance'), ('compliance', 'Compliance'), ('customer_satisfaction', 'Customer Satisfaction'), ('content_quality', 'Content Quality')], max_length=30)),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('component_scores', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.CharField(default='system', max_length=50)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('requires_immediate_action', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account Health Score',
                'verbose_name_plural': 'Account Health Scores',
                'db_table': 'account_health_scores',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('content_filter', 'Content Filter'), ('image_analysis', 'Image Analysis'), ('behavior_detection', 'Behavior Detection'), ('duplicate_detection', 'Duplicate Detection'), ('price_anomaly', 'Price Anomaly Detection'), ('review_spam', 'Review Spam Detection')], max_length=30)),
                ('conditions', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('flag_for_review', 'Flag for Review'), ('auto_reject', 'Auto Reject'), ('auto_approve', 'Auto Approve'), ('hold_for_manual', 'Hold for Manual Review'), ('escalate', 'Escalate to Senior Moderator')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('applies_to', models.JSONField(blank=True, default=list)),
                ('times_triggered', models.PositiveIntegerField(default=0)),
                ('false_positives', models.PositiveIntegerField(default=0)),
                ('true_positives', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Moderation Rule',
                'verbose_name_plural': 'Auto Moderation Rules',
                'db_table': 'auto_moderation_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('copyright', 'Copyright Violation'), ('counterfeit', 'Counterfeit Product'), ('misleading', 'Misleading Information'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('priority_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Flag',
                'verbose_name_plural': 'Content Flags',
                'db_table': 'content_flags',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve_product', 'Approve Product'), ('reject_product', 'Reject Product'), ('block_product', 'Block Product'), ('approve_seller', 'Approve Seller'), ('reject_seller', 'Reject Seller'), ('suspend_seller', 'Suspend Seller'), ('approve_kyc', 'Approve KYC'), ('reject_kyc', 'Reject KYC'), ('request_kyc_info', 'Request More KYC Info'), ('approve_ad', 'Approve Ad'), ('reject_ad', 'Reject Ad'), ('pause_ad', 'Pause Ad'), ('approve_coupon', 'Approve Coupon'), ('reject_coupon', 'Reject Coupon'), ('deactivate_coupon', 'Deactivate Coupon'), ('approve_review', 'Approve Review'), ('reject_review', 'Reject Review'), ('flag_review', 'Flag Review'), ('warn_user', 'Warn User'), ('suspend_user', 'Suspend User'), ('ban_user', 'Ban User'), ('feature_product', 'Feature Product'), ('unfeature_product', 'Unfeature Product'), ('update_seller_tier', 'Update Seller Tier')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('is_automated', models.BooleanField(default=False)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
                'db_table': 'moderation_actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
