# Generated by Django 5.2.7 on 2025-11-02 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('moderation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentflag',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accounthealthscore',
            index=models.Index(fields=['seller', 'score_type'], name='account_hea_seller__0baf29_idx'),
        ),
        migrations.AddIndex(
            model_name='accounthealthscore',
            index=models.Index(fields=['score', 'evaluated_at'], name='account_hea_score_4dacd8_idx'),
        ),
        migrations.AddIndex(
            model_name='accounthealthscore',
            index=models.Index(fields=['requires_immediate_action', 'is_critical'], name='account_hea_require_7ddaa4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accounthealthscore',
            unique_together={('seller', 'score_type', 'evaluated_at')},
        ),
        migrations.AddIndex(
            model_name='contentflag',
            index=models.Index(fields=['status', 'priority_score'], name='content_fla_status_7a8048_idx'),
        ),
        migrations.AddIndex(
            model_name='contentflag',
            index=models.Index(fields=['flag_type', 'created_at'], name='content_fla_flag_ty_c28fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='contentflag',
            index=models.Index(fields=['content_type', 'object_id'], name='content_fla_content_8a09cd_idx'),
        ),
        migrations.AddIndex(
            model_name='contentflag',
            index=models.Index(fields=['reporter', 'created_at'], name='content_fla_reporte_3a780a_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator', 'created_at'], name='moderation__moderat_436aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type', 'created_at'], name='moderation__action__75b9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['content_type', 'object_id'], name='moderation__content_22500c_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['is_automated', 'created_at'], name='moderation__is_auto_edaae4_idx'),
        ),
    ]
