# Generated by Django 5.2.7 on 2025-11-02 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('products', '0002_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='products.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='products.product'),
        ),
        migrations.AddField(
            model_name='ad',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='eligible_categories',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='products.category'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='eligible_sellers',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='sellers.sellerprofile'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='ads_status_f27728_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['placement', 'status'], name='ads_placeme_04d856_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['seller', 'status'], name='ads_seller__8bc1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date'], name='campaigns_status_389946_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type', 'status'], name='campaigns_campaig_93ffcd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_featured', 'status'], name='campaigns_is_feat_389764_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_code_94ae53_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status', 'valid_from', 'valid_to'], name='coupons_status_848fde_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['seller', 'status'], name='coupons_seller__b9e35e_idx'),
        ),
    ]
