# Generated by Django 5.2.7 on 2025-11-02 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('kyc_needs_info', 'KYC Needs More Information'), ('product_published', 'Product Published'), ('product_out_of_stock', 'Product Out of Stock'), ('product_back_in_stock', 'Product Back in Stock'), ('price_drop', 'Price Drop'), ('new_product_from_followed', 'New Product from Followed Store'), ('campaign_started', 'Campaign Started'), ('campaign_ending_soon', 'Campaign Ending Soon'), ('coupon_available', 'New Coupon Available'), ('order_placed', 'Order Placed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_received', 'Payment Received'), ('payout_processed', 'Payout Processed'), ('new_review', 'New Review'), ('review_reply', 'Review Reply'), ('account_suspended', 'Account Suspended'), ('policy_update', 'Policy Update'), ('system_maintenance', 'System Maintenance'), ('store_followed', 'Store Followed'), ('wishlist_item_low_stock', 'Wishlist Item Low Stock'), ('seller_message', 'Seller Message')], max_length=50, unique=True)),
                ('subject_template', models.CharField(max_length=255)),
                ('html_template', models.TextField()),
                ('text_template', models.TextField(blank=True)),
                ('template_variables', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('disable_all_email', models.BooleanField(default=False)),
                ('disable_all_push', models.BooleanField(default=False)),
                ('disable_all_sms', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('max_email_per_day', models.PositiveIntegerField(default=50)),
                ('max_push_per_day', models.PositiveIntegerField(default=100)),
                ('max_sms_per_day', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('kyc_needs_info', 'KYC Needs More Information'), ('product_published', 'Product Published'), ('product_out_of_stock', 'Product Out of Stock'), ('product_back_in_stock', 'Product Back in Stock'), ('price_drop', 'Price Drop'), ('new_product_from_followed', 'New Product from Followed Store'), ('campaign_started', 'Campaign Started'), ('campaign_ending_soon', 'Campaign Ending Soon'), ('coupon_available', 'New Coupon Available'), ('order_placed', 'Order Placed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_received', 'Payment Received'), ('payout_processed', 'Payout Processed'), ('new_review', 'New Review'), ('review_reply', 'Review Reply'), ('account_suspended', 'Account Suspended'), ('policy_update', 'Policy Update'), ('system_maintenance', 'System Maintenance'), ('store_followed', 'Store Followed'), ('wishlist_item_low_stock', 'Wishlist Item Low Stock'), ('seller_message', 'Seller Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('short_message', models.CharField(blank=True, max_length=160)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('send_email', models.BooleanField(default=True)),
                ('send_push', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_in_app', models.BooleanField(default=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('push_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sms_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('batch_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
